# Generated by Django 5.2.17 on 2026-09-18 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã thiết bị')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('device_type', models.CharField(choices=[('LIGHT', 'Đèn'), ('FAN', 'Quạt'), ('OTHER', 'Khác')], default='OTHER', max_length=20, verbose_name='Loại thiết bị')),
                ('node_id', models.CharField(default='esp8266_room01', max_length=50, verbose_name='Mã bo mạch')),
                ('gpio_pin', models.CharField(max_length=10, verbose_name='Chân GPIO')),
                ('current_state', models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt')], default='OFF', max_length=10, verbose_name='Trạng thái hiện tại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('node_id', 'gpio_pin'), name='device_node_gpio_unique'), models.CheckConstraint(condition=models.Q(('current_state__in', ['ON', 'OFF'])), name='device_state_valid'), models.CheckConstraint(condition=models.Q(('device_type__in', ['LIGHT', 'FAN', 'OTHER'])), name='device_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Mã yêu cầu')),
                ('action', models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt')], max_length=10, verbose_name='Hành động')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], db_index=True, default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do thất bại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi lệnh')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm kết thúc lệnh')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thao tác')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='devices.device', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Lịch sử thao tác',
                'verbose_name_plural': 'Lịch sử thao tác',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_action_created_desc'), models.Index(fields=['device', '-created_at'], name='idx_action_dev_created'), models.Index(condition=models.Q(('status', 'PENDING')), fields=['created_at'], name='idx_action_pending')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['ON', 'OFF'])), name='action_action_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESS', 'FAILED'])), name='action_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('responded_at__isnull', True), ('status', 'PENDING')), models.Q(models.Q(('status', 'PENDING'), _negated=True), ('responded_at__isnull', False)), _connector='OR'), name='action_responded_consistency')],
            },
        ),
    ]
