# Generated by Django 5.2.17 on 2026-09-18 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã cảm biến')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('metric_type', models.CharField(choices=[('TEMPERATURE', 'Nhiệt độ'), ('HUMIDITY', 'Độ ẩm'), ('LIGHT', 'Ánh sáng')], max_length=20, verbose_name='Đại lượng đo')),
                ('unit', models.CharField(max_length=10, verbose_name='Đơn vị')),
                ('hardware_model', models.CharField(blank=True, max_length=50, verbose_name='Model phần cứng')),
                ('node_id', models.CharField(default='esp8266_room01', max_length=50, verbose_name='Mã bo mạch')),
                ('min_value', models.FloatField(verbose_name='Ngưỡng dưới hợp lệ')),
                ('max_value', models.FloatField(verbose_name='Ngưỡng trên hợp lệ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cảm biến',
                'verbose_name_plural': 'Cảm biến',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('node_id', 'metric_type'), name='sensordevice_node_metric_unique'), models.CheckConstraint(condition=models.Q(('metric_type__in', ['TEMPERATURE', 'HUMIDITY', 'LIGHT'])), name='sensordevice_metric_valid'), models.CheckConstraint(condition=models.Q(('min_value__lt', models.F('max_value'))), name='sensordevice_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Giá trị đo')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm ghi nhận')),
                ('sensor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='sensors.sensordevice', verbose_name='Cảm biến')),
            ],
            options={
                'verbose_name': 'Số đo cảm biến',
                'verbose_name_plural': 'Số đo cảm biến',
                'ordering': ['-recorded_at', 'sensor_id'],
                'indexes': [models.Index(fields=['-recorded_at', 'sensor_id'], name='idx_sensordata_recorded_desc')],
                'constraints': [models.UniqueConstraint(fields=('sensor', 'recorded_at'), name='sensordata_sensor_time_unique'), models.CheckConstraint(condition=models.Q(('value__gte', -1000), ('value__lte', 100000)), name='sensordata_value_sane')],
            },
        ),
    ]
